export const CART_ACTOIN_TYPE = {
  SET_CART_IS_OPEN: "cart/SET_CART_IS_OPEN",
  ADD_CART_ITEMS: "cart/ADD_CART_ITEMS",
  REMOVE_CART_ITEM: "cart/REMOVE_CART_ITEM",
  CLEARE_CART_ITEM: "cart/CLEARE_CART_ITEM",
};
